name: Update Ayush Stats SVG

on:
  schedule:
    # Runs at these UTC times (IST is UTC+5:30)
    # Corresponding IST times: 00:00, 08:00, 12:00, 15:00, 18:00, 21:00
    - cron: '30 18 * * *'  # 00:00 IST
    - cron: '30 2 * * *'   # 08:00 IST
    - cron: '30 6 * * *'   # 12:00 IST
    - cron: '30 9 * * *'   # 15:00 IST
    - cron: '30 12 * * *'  # 18:00 IST
    - cron: '30 15 * * *'  # 21:00 IST
  workflow_dispatch:

jobs:
  update-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Fetch GitHub stats SVG
        run: |
          curl -s "https://github-readme-stats.vercel.app/api?username=CodesByAyushShivam&show_icons=true&theme=github_dark&count_private=true" > assets/ayush.svg

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/ayush.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub stats SVG [skip ci]" && git push)
